### ISSUE TITLE
set logging interval time

### ISSUE THREAD

**Issue by BenRoe** [nobodyinperson/co2monitor#16]
Thank you for the working software.
Is it possible to set an interval time. If the software writes every 10sec the data in the csv file, it will very big after some time.
Does it split the file after some time (day/month files)?

**Comment by nobodyinperson** [comment]
At the moment, data is read at the highest frequency possible. The devices give data around every 10 seconds. No, the file does not split automatically. Every time logging is started (i.e. device is plugged in or you tell co2monitor via dbus to log from a device by hand) a new file is created.
Of course, it is possible to add a configurable sleep interval after every reading... But why drop important data?

**Comment by BenRoe** [comment]
Maybe some people dont need the data every 10 sec and it wil reduce the file size.

**Comment by nobodyinperson** [comment]
Probably. I will look into adding a configurable sleep interval between readings. But I am pretty busy at the moment. This may take some time.

**Comment by nobodyinperson** [comment]
As of 31a6e13f0e8f5eabd9adb5187cc35119d88b5c1c - [v0.0.13](https://github.com/nobodyinperson/co2monitor/releases/tag/v0.0.13) you may specify an idle interval between readings in seconds in the service configuration file `/etc/co2monitor/service.conf`.

**Comment by nobodyinperson** [comment]
Keep in mind, that a new row of data is only written to file if either temperature or co2 *changed*. This also reduces file size to a minimum while keeping the maximum of information available.
